# Generated by Django 4.2.5 on 2024-01-31 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Screening', '0005_alter_agg_sc_citizen_vital_info_pulse_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_sc_citizen_pycho_info',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pycho_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agg_sc_citizen_pycho_info',
            name='modify_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pycho_modify_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
