# Generated by Django 4.2.5 on 2024-01-31 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Screening', '0009_alter_agg_sc_citizen_audit_info_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_sc_citizen_immunization_info',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immunisation_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agg_sc_citizen_immunization_info',
            name='modify_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immunisation_modify_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
