# Generated by Django 4.2.5 on 2024-02-05 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Screening', '0011_alter_agg_sc_basic_screening_info_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_Emplyee_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_screenings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_joining_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_mid_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_modify_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_by_screenings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_ref_id',
            field=models.CharField(blank=True, max_length=110, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_senior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_specialization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_com_colleague',
            name='clg_status',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_mas_group',
            name='grp_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_mas_group',
            name='grp_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_mas_group',
            name='grp_parent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
