# Generated by Django 4.2.5 on 2024-01-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screening', '0017_alter_agg_com_colleague_clg_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_sc_add_new_source',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='agg_sc_add_new_source',
            name='registration_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='agg_sc_add_new_source',
            name='source_names',
            field=models.CharField(max_length=255),
        ),
    ]
