# Generated by Django 4.2.5 on 2024-01-18 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Screening', '0018_alter_agg_sc_add_new_source_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_sc_schedule_screening',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Screening.agg_sc_class'),
        ),
        migrations.AlterField(
            model_name='agg_sc_schedule_screening',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Screening.agg_sc_screening_for_type'),
        ),
    ]
