# Generated by Django 4.2.5 on 2024-01-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screening', '0026_alter_agg_sc_add_new_source_registration_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_sc_add_new_source',
            name='Registration_details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
