# Generated by Django 4.2.5 on 2024-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Screening', '0046_alter_agg_sc_add_new_citizens_permanant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_sc_add_new_citizens',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
